---
title: "Untitled"
author: "Tom Wheeler"
date: '2022-06-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(igraph)
library(tidyverse)
library(visNetwork) 

#Import raw company profile sheet
data_sheet_company_raw <- read.xlsx2(here('data',"DataCenterEnergyUse-RawCollection.xlsx"), 2, #the "2" specifies to import sheet 2
                                     
                                     #specify column data types to ensure proper recognition
                                     colClasses=c("character","character","character","integer","Date", #columns 1-5
                                                  "character","character","character","character","character", #columns 6-10
                                                  "character","character","character","character","character", #columns 11-15
                                                  "character","character","character","character","character", #columns 16-20
                                                  "character","character","character","character","character", #columns 21-25
                                                  "character","character","character","character","character", #columns 26-30
                                                  "character","character","character","character","character", #columns 31-35
                                                  "character","character","character","character")) #column 36-39

#move second row values to column headers, put header names in tidy format and filter by only companies that have been checked back to 2007
data_sheet_company_raw <- data_sheet_company_raw %>% 
  row_to_names(2) %>% 
  clean_names() %>%
  select(!c(who_added_the_company, x, qts, x2019, x_2, x_3, x_4)) %>% 
  filter(checked_back_to_founding_year_or_2007 == "Yes")

#change column names that were set to incorrect values when column classes were set
colnames(data_sheet_company_raw) [3] <- 'company_founding_year'
colnames(data_sheet_company_raw) [4] <- 'date_last_updated'

```


```{r}
#Full network graph - basic

full_network_links <- data_sheet_company_raw %>% 
  select('company_name', 'provider_1', 'provider_2', 'provider_3', 'provider_4', 'provider_5', 'provider_6', 'provider_7', 'provider_8', 'provider_9', 'provider_10') %>% 
  pivot_longer(!company_name, names_to = 'provider', values_to = "name_of_provider") %>% 
  select('company_name', 'name_of_provider') %>% 
  na_if("") %>%
  na.omit %>% 
  rename("from" = company_name, "to" = name_of_provider)

leasers_and_leasees <- intersect(full_network_links$to, full_network_links$from)

full_network_nodes <- data.frame(id = c(full_network_links$to, full_network_links$from)) %>% 
  distinct() %>% 
  mutate(leaser.type = ifelse(id %in% full_network_links$from, 1, 2)) %>% 
  mutate(leaser.type = ifelse(id %in% leasers_and_leasees, 3, leaser.type)) %>% 
  mutate(leaser.type.name = case_when(leaser.type == 1 ~ "Leasor",
                                      leaser.type == 2 ~ "Leasee",
                                      leaser.type == 3 ~ "Leasor/Leasee"))

#visNetwork(full_network_nodes, full_network_links, width="100%", height="400px")
```

```{r}
#Full network graph - advanced

vis.nodes <- full_network_nodes
vis.links <- full_network_links

vis.nodes$shape  <- "dot"  
vis.nodes$shadow <- TRUE # Nodes will drop shadow
vis.nodes$title  <- vis.nodes$leaser.type.name # Text on click
vis.nodes$label  <- vis.nodes$id # Node label
#vis.nodes$size   <- vis.nodes$audience.size # Node size
#vis.nodes$borderWidth <- 2 # Node border width

vis.nodes$color.background <- c("slategrey", "tomato", "gold")[full_network_nodes$leaser.type]
vis.nodes$color.border <- "black"
vis.nodes$color.highlight.background <- "orange"
vis.nodes$color.highlight.border <- "darkred"
vis.links$arrows <- "middle"

visNetwork(vis.nodes, vis.links)
```


```{r}
#Selected company network graph
example_selected_company <- "Apple"
```


```{r}
example_list <- c("Data Center Lease Provider 1", "Data Center Lease Provider 2", "Data Center Lease Provider 3", "Google")

example_list <- graph_from_adj_list("Data Center Lease Provider 1", "Data Center Lease Provider 2", "Data Center Lease Provider 3", "Google")

plot(example_list)
```

```{r}
actors <- data.frame(name=c("Alice", "Bob", "Cecil", "David",
                            "Esmeralda"),
                     age=c(48,33,45,34,21),
                     gender=c("F","M","F","M","F"))
relations <- data.frame(from=c("Bob", "Cecil", "Cecil", "David",
                               "David", "Esmeralda"),
                        to=c("Alice", "Bob", "Alice", "Alice", "Bob", "Alice"),
                        same.dept=c(FALSE,FALSE,TRUE,FALSE,FALSE,TRUE),
                        friendship=c(4,5,5,2,1,1), advice=c(4,5,5,4,2,3))
g <- graph_from_data_frame(relations, directed=TRUE, vertices=actors)
plot(g)

## The opposite operation
as_data_frame(g, what="vertices")
as_data_frame(g, what="edges")
```

