---
title: "Data Center Energy Use Dashboard"
author: "Tom Wheeler"
date: "5/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(readxl)
library(xlsx)

```

## Data import and prepping spreadsheet for calculating standardized energy values

```{r}

#import data spreadsheet, specify column data types to ensure proper recognition
data_sheet <- read.xlsx2(here('data',"DataCenterEnergyUse-RawCollection.xlsx"), 1,
                             colClasses=c("character","integer","Date","Date","character", #columns 1-5
                                          "character","character","numeric","integer", "character", #columns 6-10
                                          "character","character","character","numeric","integer", #columns 11-15 (Fuel 1)
                                          "character","character","character","numeric","integer", #columns 15-20 (Fuel 2)
                                          "character","character","character","numeric","integer", #columns 21-25 (Fuel 3)
                                          "character","character","character","numeric","integer", #columns 26-30 (Fuel 4)
                                          "character","character","character","numeric","integer", #columns 31-35 (Fuel 5)
                                          "character")) #column 36 (Notes)

#move second row values to column headers, put header names in tidy format
data_sheet <- data_sheet %>% 
  row_to_names(1) %>% 
  clean_names()

#change column names that were set to incorrect values when column classes were set
colnames(data_sheet) [2] <- 'report_year'
colnames(data_sheet) [3] <- 'period_covered_start_date'
colnames(data_sheet) [4] <- 'period_covered_end_date'
colnames(data_sheet) [5] <- 'energy_reporting_scope'
colnames(data_sheet) [8] <- 'electricity_value'
colnames(data_sheet) [9] <- 'unit_scale'
colnames(data_sheet) [14] <- 'fuel_1_value'
colnames(data_sheet) [15] <- 'fuel_1_unit_scale'
colnames(data_sheet) [19] <- 'fuel_2_value'
colnames(data_sheet) [20] <- 'fuel_2_unit_scale'
colnames(data_sheet) [24] <- 'fuel_3_value'
colnames(data_sheet) [25] <- 'fuel_3_unit_scale'
colnames(data_sheet) [29] <- 'fuel_4_value'
colnames(data_sheet) [30] <- 'fuel_4_unit_scale'
colnames(data_sheet) [34] <- 'fuel_5_value'
colnames(data_sheet) [35] <- 'fuel_5_unit_scale'

#multiple values by unit scale to generate values that are ready for unit conversion

data_sheet <- data_sheet %>% 
  
  #replace any unit_scale NA values with 1
  mutate(unit_scale = replace_na(unit_scale, 1)) %>%
  mutate(fuel_1_unit_scale = replace_na(fuel_1_unit_scale, 1)) %>%
  mutate(fuel_2_unit_scale = replace_na(fuel_2_unit_scale, 1)) %>%
  mutate(fuel_3_unit_scale = replace_na(fuel_3_unit_scale, 1)) %>%
  mutate(fuel_4_unit_scale = replace_na(fuel_4_unit_scale, 1)) %>%
  mutate(fuel_5_unit_scale = replace_na(fuel_5_unit_scale, 1)) %>%
  
  #multiply electricity and fuel values by unit scale
  mutate(electricity_prepped = electricity_value * unit_scale, .after = unit_scale) %>% 
  mutate(fuel_1_prepped = fuel_1_value * fuel_1_unit_scale, .after = fuel_1_unit_scale) %>% 
  mutate(fuel_2_prepped = fuel_2_value * fuel_2_unit_scale, .after = fuel_2_unit_scale) %>% 
  mutate(fuel_3_prepped = fuel_3_value * fuel_3_unit_scale, .after = fuel_3_unit_scale) %>% 
  mutate(fuel_4_prepped = fuel_4_value * fuel_4_unit_scale, .after = fuel_4_unit_scale) %>% 
  mutate(fuel_5_prepped = fuel_5_value * fuel_5_unit_scale, .after = fuel_5_unit_scale)

data_sheet <- data_sheet %>% 
  
  #merge fuel type and units to prepare for vlookup function
  unite(fuel_unit_1, c(fuel_1_type, fuel_1_unit), sep = " ", remove = FALSE) %>% 
  unite(fuel_unit_2, c(fuel_2_type, fuel_2_unit), sep = " ", remove = FALSE) %>% 
  unite(fuel_unit_3, c(fuel_3_type, fuel_3_unit), sep = " ", remove = FALSE) %>% 
  unite(fuel_unit_4, c(fuel_4_type, fuel_4_unit), sep = " ", remove = FALSE) %>% 
  unite(fuel_unit_5, c(fuel_5_type, fuel_5_unit), sep = " ", remove = FALSE)

```

## Calculate energy unit conversions to base unit (kWh) and add to data_sheet

```{r}
#import conversions spreadsheet, select columns data types, clean header names, select columns, unite fuel and unit columns
conversions_sheet <- read.xlsx2(here('data',"DataCenterEnergyUse-RawCollection.xlsx"), 3,
                                colClasses=c("character", "character", "character", "numeric")) %>% 
                                clean_names() %>% 
                                select('fuel', 'unit', 'k_wh_1_unit') %>% 
                                drop_na() %>% 
                                unite('fuel_unit', fuel:unit, sep = " ", remove = FALSE)

######################################
#calculate conversion for electricity#
######################################

#isolate electricity values and respective units into dataframe
electricity_data <- data_sheet %>% 
  select('electricity_prepped', 'unit') %>% 
  relocate(electricity_prepped, .after = unit)

#select just unit column and the relevant conversion because electricity values do not have an associated fuel
conversions_sheet_electricity <- conversions_sheet %>%
  select('unit', 'k_wh_1_unit') %>% 
  distinct()

#join and match unit conversion factor for electricity values (i.e. if MWh value should be multiplied by 1000)
electricity_conversion <- left_join(electricity_data, conversions_sheet_electricity, by="unit") %>% 
  mutate(electricity_converted = electricity_prepped * k_wh_1_unit)

#################################
#calculate conversions for fuels#
#################################

#FUEL 1

#isolate fuel unit and prepped values into dataframe
fuel_1_data <- data_sheet %>% 
  select('fuel_unit_1', 'fuel_1_prepped')

#change name of left column from conversion sheet to match fuel number
conversions_sheet_fuel_1 <- conversions_sheet %>%
  select('fuel_unit', 'k_wh_1_unit') %>% 
  rename(fuel_unit_1 = fuel_unit)

#join and match, calculate prepped fuel value multiplied by its respective conversion
fuel_1_conversion <- left_join(fuel_1_data, conversions_sheet_fuel_1, by="fuel_unit_1") %>% 
  mutate(fuel_1_converted = fuel_1_prepped * k_wh_1_unit)

#FUEL 2

#isolate fuel unit and prepped values into dataframe
fuel_2_data <- data_sheet %>% 
  select('fuel_unit_2', 'fuel_2_prepped')

#change name of left column from conversion sheet to match fuel number
conversions_sheet_fuel_2 <- conversions_sheet %>%
  select('fuel_unit', 'k_wh_1_unit') %>% 
  rename(fuel_unit_2 = fuel_unit)

#join and match, calculate prepped fuel value multiplied by its respective conversion
fuel_2_conversion <- left_join(fuel_2_data, conversions_sheet_fuel_2, by="fuel_unit_2") %>% 
  mutate(fuel_2_converted = fuel_2_prepped * k_wh_1_unit)

#FUEL 3

#isolate fuel unit and prepped values into dataframe
fuel_3_data <- data_sheet %>% 
  select('fuel_unit_3', 'fuel_3_prepped')

#change name of left column from conversion sheet to match fuel number
conversions_sheet_fuel_3 <- conversions_sheet %>% 
  select('fuel_unit', 'k_wh_1_unit') %>% 
  rename(fuel_unit_3 = fuel_unit)

#join and match, calculate prepped fuel value multiplied by its respective conversion
fuel_3_conversion <- left_join(fuel_3_data, conversions_sheet_fuel_3, by="fuel_unit_3") %>% 
  mutate(fuel_3_converted = fuel_3_prepped * k_wh_1_unit)

#FUEL 4

#isolate fuel unit and prepped values into dataframe
fuel_4_data <- data_sheet %>% 
  select('fuel_unit_4', 'fuel_4_prepped')

#change name of left column from conversion sheet to match fuel number
conversions_sheet_fuel_4 <- conversions_sheet %>%
  select('fuel_unit', 'k_wh_1_unit') %>% 
  rename(fuel_unit_4 = fuel_unit)

#join and match, calculate prepped fuel value multiplied by its respective conversion
fuel_4_conversion <- left_join(fuel_4_data, conversions_sheet_fuel_4, by="fuel_unit_4") %>% 
  mutate(fuel_4_converted = fuel_4_prepped * k_wh_1_unit)

#FUEL 5

#isolate fuel unit and prepped values into dataframe
fuel_5_data <- data_sheet %>% 
  select('fuel_unit_5', 'fuel_5_prepped')

#change name of left column from conversion sheet to match fuel number
conversions_sheet_fuel_5 <- conversions_sheet %>% 
  select('fuel_unit', 'k_wh_1_unit') %>% 
  rename(fuel_unit_5 = fuel_unit)

#join and match, calculate prepped fuel value multiplied by its respective conversion
fuel_5_conversion <- left_join(fuel_5_data, conversions_sheet_fuel_5, by="fuel_unit_5") %>% 
  mutate(fuel_5_converted = fuel_5_prepped * k_wh_1_unit)

#Bind converted values to data_sheet, move columns next to fuel_1_prepped for easier viewing
data_sheet <- cbind(data_sheet, electricity_conversion["electricity_converted"],
                    fuel_1_conversion["fuel_1_converted"], 
                    fuel_2_conversion["fuel_2_converted"],
                    fuel_3_conversion["fuel_3_converted"],
                    fuel_4_conversion["fuel_4_converted"],
                    fuel_5_conversion["fuel_5_converted"]) %>% 
              relocate(fuel_1_converted, .after = fuel_1_prepped) %>% 
              relocate(fuel_2_converted, .after = fuel_2_prepped) %>%
              relocate(fuel_3_converted, .after = fuel_3_prepped) %>%
              relocate(fuel_4_converted, .after = fuel_4_prepped) %>%
              relocate(fuel_5_converted, .after = fuel_5_prepped)
```

## Merge fuel converted values into a separate spreadsheet to prepare for graphing

```{r}
#isolate electricity values
data_sheet_electricity <- data_sheet %>% 
  select("company", "report_year", "electricity_converted") %>% 
  add_column(fuel_type = "Electricity") %>% 
  relocate("fuel_type", .after = report_year) %>% 
  rename(value = electricity_converted)

#isolate fuel 1 values
data_sheet_combined_1 <- data_sheet %>% 
  select("company", "report_year", "fuel_1_type", "fuel_1_converted") %>% 
  rename(fuel_type = fuel_1_type) %>% 
  rename(value = fuel_1_converted)

#isolate fuel 2 values
data_sheet_combined_2 <- data_sheet %>% 
  select("company", "report_year", "fuel_2_type", "fuel_2_converted") %>% 
  rename(fuel_type = fuel_2_type) %>% 
  rename(value = fuel_2_converted)

#isolate fuel 3 values
data_sheet_combined_3 <- data_sheet %>% 
  select("company", "report_year", "fuel_3_type", "fuel_3_converted") %>% 
  rename(fuel_type = fuel_3_type) %>% 
  rename(value = fuel_3_converted)

#isolate fuel 4 values
data_sheet_combined_4 <- data_sheet %>% 
  select("company", "report_year", "fuel_4_type", "fuel_4_converted") %>% 
  rename(fuel_type = fuel_4_type) %>% 
  rename(value = fuel_4_converted)

#isolate fuel 5 values
data_sheet_combined_5 <- data_sheet %>% 
  select("company", "report_year", "fuel_5_type", "fuel_5_converted") %>% 
  rename(fuel_type = fuel_5_type) %>% 
  rename(value = fuel_5_converted)

```

``` {r}
#electricity and all fuel values on top of each other, drop columns with NA (filter by Apple for example plotting)
data_sheet_graph_1 <- rbind(data_sheet_electricity, data_sheet_combined_1, 
                          data_sheet_combined_2, data_sheet_combined_3,
                          data_sheet_combined_4, data_sheet_combined_5) %>%  
                    drop_na() %>% 
                    filter(company == "Huawei") %>% 
                    arrange(desc(report_year))

data_sheet_graph_2 <- data_sheet %>% 
  mutate_at(vars(electricity_converted, fuel_1_converted, 
           fuel_2_converted, fuel_3_converted, fuel_4_converted, 
           fuel_5_converted), ~replace_na(., 0)) %>%
  rowwise() %>% 
  mutate(total_energy_use = sum(electricity_converted, fuel_1_converted, 
           fuel_2_converted, fuel_3_converted, fuel_4_converted, 
           fuel_5_converted)) %>% 
  relocate(total_energy_use, .after = notes) %>%
  unite('scope_display_label', energy_reporting_scope:display_label, sep = " | ") %>% 
  select("company", "report_year", "scope_display_label", "total_energy_use") %>% 
  mutate_at(vars(total_energy_use), as.numeric) %>% 
                    filter(company == "Facebook")
```

```{r}
# Stacked
ggplot(data_sheet_graph_1, aes(fill=fuel_type, y=value, x=report_year)) + 
    geom_bar(position="stack", stat="identity")
```

```{r}
ggplot(data_sheet_graph_2, aes(fill=scope_display_label, y=total_energy_use, x=report_year)) + 
    geom_bar(position="stack", stat="identity")
```

